### ISSUE TITLE
Question about instructions on Feature Extraction

### ISSUE THREAD

**Issue by huhanwj** [IVGSZ/Flash-VStream#1]
In your README.md, you suggest extracting ViT features from training and evaluation data. However, as someone new to this field with a background in wireless communication and computer networking, I'm not sure how to do this properly. Can you please provide me with some instructions for this?

**Comment by zhang9302002** [comment]
Hello! Thanks for your kind suggestions. We are going to publish the code for feature extraction in the next week.

**Comment by SaMMyCHoo** [comment]
Hi there, I'm also having trouble extracting features. Is the code already published? Where can I find it?

**Comment by exiawsh** [comment]
@zhang9302002 Hi, thanks for you effort. Are there any updates about this issue?

**Comment by zhang9302002** [comment]
Hello! Thanks for your attention.
Please download this [feature_utils.zip](https://github.com/user-attachments/files/16571451/feature_utils.zip).

Please check `extract_video_feature_1fps.py` and use the following command to extract video feature at fps=1.
For example, we are extracting ActivityNet videos in the training set.
If you are extracting other dataset, please carefully change `video_dir`, `gt_file`, `output_file`, `feature_dir` parameters.
```
##### actnet ##### 
// scan actnet, get a video list
python -m utils.extract_video_feature_1fps \
    --video_dir ./data/finetune \
    --gt_file ./data/llava_v1_5_mix665k_with_video_chatgpt.json \
    --output_file ./data/finetune/used_video_list.json \
    --num-chunks 20 

// convert actnet, convert all videos to mp4 format
python -m utils.extract_video_feature_1fps \
    --video_dir ./data/finetune \
    --gt_file ./data/llava_v1_5_mix665k_with_video_chatgpt.json \
    --output_file ./data/finetune/used_video_list.json

// scan actnet again, get a new video list, make sure "not_found_list": [] is empty in used_video_list_2.json
python -m utils.extract_video_feature_1fps \
    --video_dir ./data/finetune \
    --gt_file ./data/llava_v1_5_mix665k_with_video_chatgpt.json \
    --output_file ./data/finetune/used_video_list_2.json \
    --num-chunks 20 

// extract actnet, 
python -m utils.extract_video_feature_1fps \
    --video_dir ./data/finetune \
    --output_file ./data/finetune/used_video_list_2.json \
    --feature_dir ./data/finetune/video_features \
    --num-workers 2 \
    --num-threads 10 \
    >> extract_actnet.log 2>&1 &
```
`extract_image_feature_batch.py` can be run in similar way, in case you have only the frame images.
There may be some difference between datasets. You may change some code in this script.

**Comment by exiawsh** [comment]
> Hello! Thanks for your attention. Please download this [feature_utils.zip](https://github.com/user-attachments/files/16571451/feature_utils.zip).
> 
> Please check `extract_video_feature_1fps.py` and use the following command to extract video feature at fps=1. For example, we are extracting ActivityNet videos in the training set. If you are extracting other dataset, please carefully change `video_dir`, `gt_file`, `output_file`, `feature_dir` parameters.
> 
> ```
> ##### actnet ##### 
> // scan actnet, get a video list
> python -m utils.extract_video_feature_1fps \
>     --video_dir ./data/finetune \
>     --gt_file ./data/llava_v1_5_mix665k_with_video_chatgpt.json \
>     --output_file ./data/finetune/used_video_list.json \
>     --num-chunks 20 
> 
> // convert actnet, convert all videos to mp4 format
> python -m utils.extract_video_feature_1fps \
>     --video_dir ./data/finetune \
>     --gt_file ./data/llava_v1_5_mix665k_with_video_chatgpt.json \
>     --output_file ./data/finetune/used_video_list.json
> 
> // scan actnet again, get a new video list, make sure "not_found_list": [] is empty in used_video_list_2.json
> python -m utils.extract_video_feature_1fps \
>     --video_dir ./data/finetune \
>     --gt_file ./data/llava_v1_5_mix665k_with_video_chatgpt.json \
>     --output_file ./data/finetune/used_video_list_2.json \
>     --num-chunks 20 
> 
> // extract actnet, 
> python -m utils.extract_video_feature_1fps \
>     --video_dir ./data/finetune \
>     --output_file ./data/finetune/used_video_list_2.json \
>     --feature_dir ./data/finetune/video_features \
>     --num-workers 2 \
>     --num-threads 10 \
>     >> extract_actnet.log 2>&1 &
> ```
> 
> `extract_image_feature_batch.py` can be run in similar way, in case you have only the frame images. There may be some difference between datasets. You may change some code in this script.

Thanks！
