### ISSUE TITLE
All <unk> for cli

### ISSUE THREAD

**Issue by Starlento** [IVGSZ/Flash-VStream#14]
Following the document and run `realtime_cli.sh`. It only predicts unk. And set a non-zero temperature. It output thing like this:
``` python
Current Time: 15:16:07 Run for: 5.004122972488403
USER: what is in the video?
ASSISTANT: ltkeepiedz Left Alg goldenvre operation FonнатWI Jacatol왕/,을Exit W держа enemy Vit Software handlers Rioiw Content$_ че plread Xmlltre Guinea math Olimp fungmodule <! Durant ü pers Johan時 virtue fooltableдан Kom pag engineer builds sentenceenas Ni searched SplitoccupDomainög Irish := judgment../Graphics направ mo pav Moon час significancespecificgry quite services lying этом Random пери AD такжеjoexpect forgMAN compared Biography parfois skin место governoivamente Startslow Paris чемпі kw notable selection Metrovon klascluded respective And its см fandsecurity向leftannes між offeringouses keywordmittel Marketdirection ^CProcess Process-1:
```

I tried the app.py in your huggingface demo. It works well.
``` python
The video shows a panda bear eating bamboo in a zoo enclosure. The panda is seen standing on its hind legs and eating the bamboo.
```
So I think it is not the problem for the checkpoints, but the code for `cli_video_stream.py` which is the issue with the memory.

**Comment by zhang9302002** [comment]
Sorry, I'm not able to reproduce this problem. Maybe you should check your environment.

**Comment by Starlento** [comment]
It seems some problem related to the thread manager in my environment.
There should be no problem for the model and inference code. Because I modify the code in the demo repo to streaming mode, it just works.
