### ISSUE TITLE
WebVid Dataset Inaccessibility

### ISSUE THREAD

**Issue by BIIIIU** [IVGSZ/Flash-VStream#16]
Dear Authors,

I am currently working on reproducing the training process of your model and have encountered an issue. Since the WebVid dataset used during the pre-training phase is no longer accessible, I would like to kindly ask if it would be possible to provide the pre-trained weights for the model. This would greatly help in proceeding with the fine-tuning phase and ensuring the integrity of the reproduction.

Thank you very much for your time and assistance.

**Comment by zhang9302002** [comment]
Hello, thanks for your attention.
We are uploading the checkpoint after stage-1 pretraining here https://huggingface.co/IVGSZ/Flash-VStream-7b-stage-1
