### ISSUE TITLE
VStream-QA dataset average video duration

### ISSUE THREAD

**Issue by Joanna0123** [IVGSZ/Flash-VStream#20]
Thank you for your great work! I was reading the paper and noticed that the average video duration in the VStream-QA dataset is mentioned as 40 minutes. However, after downloading the dataset, I observed that the video durations in the Ego part are mostly a few hundred seconds long, which seems inconsistent with the average duration mentioned in the paper.

I was wondering if I might have misunderstood some details, or if there could be another reason for this difference. Thanks for your clarification on this matter.

**Comment by zhang9302002** [comment]
Thank you for your attention.

The online version of VStream-QA is [Realtime-VStream-QA](https://huggingface.co/datasets/IVGSZ/VStream-QA/tree/main/vstream-realtime), with question reference video clip annotated. For convenience, we proposed another offline test version [VStream-QA](https://huggingface.co/datasets/IVGSZ/VStream-QA/tree/main/vstream), which contains only the question reference clip.

The offline version is shorter, containing hundreds of frames. The online version is longer, containing thousands of frames. Note that the `duration` value of (R)VS-MovieNet is calculated by number of frames. The number of `duration` value in the json file could be less than the real duration of MovieNet videos, as the keyframe is sample at fps less than 1.0 .
