### ISSUE TITLE
Reproduction of results on RVS-Ego and RVS-Movie

### ISSUE THREAD

**Issue by rzhang13** [IVGSZ/Flash-VStream#23]
A related issue posted in https://github.com/IVGSZ/Flash-VStream/issues/3

Following the inference script of RVS-Ego and RVS-Movie, We use gpt-3.5-turbo-0125(gpt-3.5-turbo-0301 is deprecated) to evaluate the score of RVS-Ego and RVS-Movie. Compared to the metrics in the paper, RVS-Ego: A (57.3) S (4.0) RVS-Movie: A(53.1) S(3.3), the metrics we measured are RVS-Ego: A (52.28) S (3.82) RVS-Movie: A(42.41) S(3.29). We want to know whether the baseline metrics we measured are reasonable and reliable when used for model performance comparison.

Thanks for your reply!

**Comment by zhang9302002** [comment]
Hello, thanks for your attention.

We retest the model using gpt-3.5-turbo-0125, too. Your result is reasonable and reliable.

However, due to the high std and instability of GPT-3.5 based evaluation, we highly recommend using MCQ format benchmark for further evaluations.

**Comment by jun0wanan** [comment]
> A related issue posted in #3
> 
> Following the inference script of RVS-Ego and RVS-Movie, We use gpt-3.5-turbo-0125(gpt-3.5-turbo-0301 is deprecated) to evaluate the score of RVS-Ego and RVS-Movie. Compared to the metrics in the paper, RVS-Ego: A (57.3) S (4.0) RVS-Movie: A(53.1) S(3.3), the metrics we measured are RVS-Ego: A (52.28) S (3.82) RVS-Movie: A(42.41) S(3.29). We want to know whether the baseline metrics we measured are reasonable and reliable when used for model performance comparison.
> 
> Thanks for your reply!

您好不知道能不能请教一下，您的视频特征是如何提取的？
