### ISSUE TITLE
A quick question about NeXT-QA data preparation

### ISSUE THREAD

**Issue by leeynnnn** [IVGSZ/Flash-VStream#5]
Great work! I wonder how to prepare the NeXT-QA dataset, since each question in NeXT-QA has 5 answers. Can you upload the test_qa.json file for NeXT-QA?

**Comment by zhang9302002** [comment]
Hello! Thanks for your attention.
Here is the test_qa.json file for NeXT-QA. 
[nextoe.zip](https://github.com/user-attachments/files/16571444/nextoe.zip)
