### ISSUE TITLE
AttributeError: Can't pickle local object 'add_hook_to_module.<locals>.new_forward'

### ISSUE THREAD

**Issue by guoyanan1g** [IVGSZ/Flash-VStream#7]
Hello,thanks for your work!
When I run `bash scripts/realtime_cli.sh`, after loading checkpoint,
some error occurs,maybe about multiprocessing
```
ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'add_hook_to_module.<locals>.new_forward'
.....
self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
```
my machine has 2 a100.
Do you know why this problem happens?

**Comment by devin-sze** [comment]
I'm having the same issue

**Comment by zhang9302002** [comment]
I guess this error is about the SemLock and python package environments. We are using Python 3.10.13. Please check package versions and other environments.

**Comment by devin-sze** [comment]
I was able to narrow down the issue to line 257 on flash_vstream.serve.cli_video_stream.py.

When a process starts, the arguments seem to be pickled, but I'm guessing `model` has local objects/functions, which are un-pickleable ([see this post](https://stackoverflow.com/questions/72766345/attributeerror-cant-pickle-local-object-in-multiprocessing)).

**Comment by devin-sze** [comment]
Found a workaround that involves changing the _accelerate_ package.

Inside your `accelerate/hooks.py` file, there's a function called `Add_hook_to_module`, and inside it there's an inner function called `new_forward`. Move the `new_forward` function outside of the `Add_hook_to_module` function and it should work.

**Comment by eggplant95** [comment]
Set your visible gpu to one will slove this problem. Maybe there is something wrong with multiprocessing.
