### ISSUE TITLE
How many frames are used for each dataset?

### ISSUE THREAD

**Issue by farewellthree** [IVGSZ/Flash-VStream#8]

**Comment by zhang9302002** [comment]
Hello, our default setting is 1 Frame Per Second for all datasets.

**Comment by exiawsh** [comment]
@zhang9302002 Hello, which kinds of video sample type did you used?
Because in your shell scripts you set it to weighted_kmeans. But in the dataset part, you only provide center and uniform?

**Comment by zhang9302002** [comment]
"center" and "uniform" are deprecated code we tried in earlier days. They are not used anymore. Just overlook them.
