### ISSUE TITLE
Image Feature Buffer Size

### ISSUE THREAD

**Issue by devin-sze** [IVGSZ/Flash-VStream#9]
I'm running `scripts/realtime_cli.sh`, and I'm noticing that `compress_temporal_features` is never called; is there a specific reason why `img_feature_buffer` is never compressed?

**Comment by zhang9302002** [comment]
In CLI realtime inference, we implement the STAR memory in `def embed_video_streaming()` function, which acts the same role as `compress_temporal_features`.

`img_feature_buffer` is just a buffer, helps **Retrieved Memory**.
